import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { config } from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

const envPath = join(projectRoot, '.env');
if (existsSync(envPath)) {
  config({ path: envPath });
}

const CLIENT_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_PUBLISHABLE_KEY',
  'VITE_SUPABASE_PROJECT_ID',
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
];

const SERVER_ONLY_KEYS = [
  'SUPABASE_SERVICE_ROLE_KEY',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_CHAT_ID',
  'ADMIN_PASSWORD',
  'SUPABASE_DATABASE_URL',
];

const missing = [];
const envObj = {};

CLIENT_KEYS.forEach((key) => {
  let val = process.env[key] || '';
  if (!val) {
    const altKey = key.replace('VITE_', '').replace('NEXT_PUBLIC_', '');
    val = process.env[altKey] || '';
  }
  if (!val && !key.startsWith('NEXT_')) {
    missing.push(key);
  }
  envObj[key] = val;
});

// Never let a server-only secret value pass into the client file, even if it
// was mistakenly stored under a public-looking variable name.
function isSafeClientValue(val) {
  if (!val) return true;
  for (const k of SERVER_ONLY_KEYS) {
    const secret = process.env[k];
    if (secret && val.includes(secret)) return false;
  }
  if (/^(postgres(ql)?):\/\//i.test(val)) return false; // database connection strings are never client-safe
  return true;
}

function pickSafe(...candidates) {
  for (const c of candidates) {
    if (c && isSafeClientValue(c)) return c;
  }
  return '';
}

envObj.VITE_SUPABASE_URL = pickSafe(envObj.VITE_SUPABASE_URL, envObj.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_URL);
envObj.VITE_SUPABASE_PUBLISHABLE_KEY = pickSafe(envObj.VITE_SUPABASE_PUBLISHABLE_KEY, envObj.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, process.env.SUPABASE_PUBLISHABLE_KEY);
envObj.VITE_SUPABASE_PROJECT_ID = pickSafe(envObj.VITE_SUPABASE_PROJECT_ID, process.env.SUPABASE_PROJECT_ID);

// The Supabase URL must be an https URL — anything else (e.g. a postgres://
// connection string) is a misconfiguration and is dropped.
if (envObj.VITE_SUPABASE_URL && !/^https:\/\//i.test(envObj.VITE_SUPABASE_URL)) {
  console.warn('⚠️  SUPABASE_URL value is not an https URL — ignoring it.');
  envObj.VITE_SUPABASE_URL = '';
}

if (!envObj.VITE_SUPABASE_URL || !envObj.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️  Warning: Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Client-side Supabase will not work.');
}

const outDir = join(projectRoot, 'js');
if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}

const outPath = join(outDir, 'env.generated.js');
const content = `// Auto-generated by scripts/generate-env-js.mjs — do NOT edit by hand.
(function () {
  if (typeof window === 'undefined') return;
  window.__ENV = window.__ENV || {};
  window.__ENV.VITE_SUPABASE_URL = ${JSON.stringify(envObj.VITE_SUPABASE_URL)};
  window.__ENV.VITE_SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(envObj.VITE_SUPABASE_PUBLISHABLE_KEY)};
  window.__ENV.VITE_SUPABASE_PROJECT_ID = ${JSON.stringify(envObj.VITE_SUPABASE_PROJECT_ID)};
  window.__ENV.API_BASE = '/.netlify/functions';
})();
`;

const leakCheck = content;
SERVER_ONLY_KEYS.forEach((k) => {
  const v = process.env[k];
  if (v && leakCheck.includes(v)) {
    console.error(`❌ FATAL: Server-only secret ${k} leaked into generated env.generated.js!`);
    process.exit(1);
  }
});

writeFileSync(outPath, content, 'utf8');
console.log(`✅ Generated ${outPath}`);
console.log(`   Exposed to client: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY, VITE_SUPABASE_PROJECT_ID`);
console.log(`   Kept server-only: ${SERVER_ONLY_KEYS.join(', ')}`);
